import Navigation from "@/components/navigation"
import "../styles/globals.css"
import Footer from "@/components/footer"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  icons:{
    icon: "/favicon.ico"
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-black">
        <Navigation/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
